# Generated by Django 4.2.5 on 2023-09-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Routine Exams', 'routine_exams'), ('Dental Hygiene', 'dental_hygiene'), ('Veneers', 'veneers'), ('Dentures', 'dentures'), ('Teeth Whitening', 'teeth_whitening')], max_length=20),
        ),
    ]
