# Generated by Django 4.2.5 on 2023-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_message_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='insurance',
            field=models.CharField(default='1', max_length=40),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_date'], name='date_idx'),
        ),
    ]
