# Generated by Django 4.2.5 on 2023-09-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_appointment_insurance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='insurance',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=30),
        ),
    ]
