# Generated by Django 4.2.5 on 2023-09-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=400)),
                ('posted_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
